In [1]:
%pwd

'/home/benfild/Documents/dataScience_playground'

In [2]:
import numpy as np 
np.sin(90)

0.8939966636005579

In [3]:
%%time
for i in range(5):
    print(i)

0
1
2
3
4
CPU times: user 351 µs, sys: 57 µs, total: 408 µs
Wall time: 339 µs


In [4]:
np.int64(2)**1000

0

In [5]:
arr = np.array([1,2,3])

In [6]:
len(arr)

3

In [7]:
arr[1]

2

In [8]:
arr.dtype

dtype('int64')

In [10]:
type(arr[1])

numpy.int64

In [13]:
type(arr)

numpy.ndarray

In [14]:
type(arr[2])

numpy.int64

In [15]:
arr * arr

array([1, 4, 9])

In [16]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [17]:
%time v1 * v2

CPU times: user 3.07 ms, sys: 16.9 ms, total: 19.9 ms
Wall time: 19.5 ms


array([0.26800721, 0.06671057, 0.23661953, ..., 0.090849  , 0.07872204,
       0.2708926 ])

In [20]:
np.dot(arr, arr)
#or
arr @ arr

14

In [21]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
arr@arr

14

In [23]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
v = np.arange(13)

In [25]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
v.reshape((3,4))

ValueError: cannot reshape array of size 13 into shape (3,4)

In [28]:
mat = np.arange(12).reshape((3,4))

In [29]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
mat.shape

(3, 4)

In [31]:
mat2 = mat.reshape((4,3))

In [32]:
mat2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
mat[1,2] = 17

In [34]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5, 17,  7],
       [ 8,  9, 10, 11]])

In [35]:
mat.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2, 17, 10],
       [ 3,  7, 11]])

In [36]:
nums = [1,2,3,4,5,6,7]
nums[2:4]

[3, 4]

In [37]:
v = np.arange(1,6)

In [38]:
v[2:4]

array([3, 4])

In [39]:
arr = np.arange(12).reshape(3,4)

In [40]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
arr[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr[2, 1]

9

In [44]:
arr[:, 1]

array([1, 5, 9])

In [45]:
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [46]:
arr[1:, 2:] = 7

In [47]:
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

In [48]:
## BOOLEAN INDEXING

In [51]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [52]:
arr[np.array([True, False, True])]

array([0, 2])

In [53]:
arr >= 1

array([False,  True,  True])

In [54]:
arr

array([0, 1, 2])

In [55]:
arr[arr>=1]

array([1, 2])

In [56]:
arr = np.arange(10)

In [57]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [61]:
mat = np.random.rand(5, 5)

In [62]:
mat

array([[0.576161  , 0.92236136, 0.42888291, 0.65318697, 0.20970648],
       [0.26774624, 0.56105349, 0.60316778, 0.57222267, 0.2524423 ],
       [0.09561593, 0.69439802, 0.40318709, 0.3550278 , 0.37707796],
       [0.70863261, 0.71843298, 0.5405134 , 0.45675504, 0.34624789],
       [0.21174209, 0.9105291 , 0.50064457, 0.274285  , 0.54796978]])

In [63]:
np.abs(mat - mat.mean())

array([[0.08864138, 0.43484174, 0.05863671, 0.16566736, 0.27781313],
       [0.21977338, 0.07353387, 0.11564816, 0.08470305, 0.23507732],
       [0.39190368, 0.2068784 , 0.08433253, 0.13249182, 0.11044166],
       [0.22111299, 0.23091336, 0.05299378, 0.03076458, 0.14127173],
       [0.27577753, 0.42300949, 0.01312496, 0.21323461, 0.06045017]])

In [64]:
np.abs(mat - mat.mean()) > 1.5*mat.std()

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [67]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([0.92236136, 0.09561593, 0.9105291 ])

In [68]:
mat.mean()

0.4875196186770475

In [69]:
v = np.arange(12).reshape((4,3))

In [70]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [72]:
v.shape

(4, 3)

In [75]:
v.conjugate()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
v.any

<function ndarray.any>

In [37]:
v.any()

True

In [38]:
v.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [76]:
v.all()

False

In [77]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [78]:
v[(0,0)] = 12

In [79]:
v

array([[12,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
v.prod()

479001600

In [81]:
v1 = v.copy()

In [82]:
v1[0,0] = 1234

In [83]:
v1

array([[1234,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [84]:
v

array([[12,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [86]:
v2 = np.loads(data)
v2

<ipython-input-86-b770a7d8cac2>:1: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
  v2 = np.loads(data)


array([[12,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [88]:
v = np.arange(-3,3)

In [89]:
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [90]:
v

array([-3, -2, -1,  0,  1,  2])

In [92]:
def noneg(n):
    if n<0:
        return 0
    return n

noneg(7)

7

In [93]:
noneg(-3)

0

In [94]:
noneg(v)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [95]:
## VECTORIZED FUNCTION
# it's a function that takes a regular function and converts it to ufunc.
# The easiest way to do this is to use vectorize as a decorator
# Decorators are functions that get functions as arguments and returns function

@np.vectorize
def noneg(n):
    if n<0:
        return 0
    return n

In [96]:
# The above cell is the same as this cell

def noneg(n):
    if n<0:
        return 0
    return n
noneg = np.vectorize(noneg)

In [97]:
noneg(3)

array(3)

In [98]:
# we can use noneg of vector v
noneg(v)

array([0, 0, 0, 0, 1, 2])