In [1]:
%pwd

'/home/benfild/Documents/Data science '

In [3]:
import numpy as np 
np.sin(90)

0.8939966636005579

In [4]:
%%time
for i in range(5):
    print(i)

0
1
2
3
4
CPU times: user 955 µs, sys: 46 µs, total: 1 ms
Wall time: 742 µs


In [6]:
np.int64(2)**1000

0

In [7]:
arr = np.array([1,2,3])

In [8]:
len(arr)

3

In [9]:
arr[1]

2

In [11]:
arr.dtype

dtype('int64')

In [12]:
type[arr[1]]

type[2]

In [14]:
type(arr)

numpy.ndarray

In [15]:
type(arr[2])

numpy.int64

In [16]:
arr * arr

array([1, 4, 9])

In [17]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [18]:
%time v1 * v2

CPU times: user 29 µs, sys: 16.5 ms, total: 16.5 ms
Wall time: 20.5 ms


array([0.04566288, 0.31932251, 0.04975691, ..., 0.24755744, 0.10707069,
       0.27715801])

In [20]:
np.dot(arr, arr)

14

In [22]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
arr@arr

14

In [24]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
v = np.arange(13)

In [27]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
v.reshape((3,4))

ValueError: cannot reshape array of size 13 into shape (3,4)

In [29]:
mat = np.arange(12).reshape((3,4))

In [30]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
mat.shape

(3, 4)

In [32]:
mat2 = mat.reshape((4,3))

In [33]:
mat2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
mat[1,2] = 17

In [35]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5, 17,  7],
       [ 8,  9, 10, 11]])

In [36]:
mat.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2, 17, 10],
       [ 3,  7, 11]])

In [1]:
nums = [1,2,3,4,5,6,7]
nums[2:4]

[3, 4]

In [4]:
v = np.arange(1,6)

In [6]:
v[2:4]

array([3, 4])

In [7]:
arr = np.arange(12).reshape(3,4)

In [8]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arr[2, 1]

9

In [13]:
arr[:, 1]

array([1, 5, 9])

In [14]:
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [15]:
arr[1:, 2:] = 7

In [18]:
arr

array([0, 1, 2])

In [19]:
## BOOLEAN INDEXING

In [17]:
arr = np.arange(3)

In [20]:
arr[np.array([True, False, True])]

array([0, 2])

In [21]:
arr >= 1

array([False,  True,  True])

In [22]:
arr

array([0, 1, 2])

In [23]:
arr[arr>=1]

array([1, 2])

In [24]:
arr = np.arange(10)

In [26]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [27]:
mat = np.random.rand(5, 5)

In [28]:
mat

array([[0.24082761, 0.43897707, 0.81373251, 0.31551228, 0.11186613],
       [0.02261373, 0.89766909, 0.77994735, 0.33942165, 0.13082179],
       [0.02591456, 0.45290589, 0.41746377, 0.91002682, 0.19876839],
       [0.49396369, 0.89111861, 0.6757307 , 0.00690147, 0.44741585],
       [0.95691825, 0.64411178, 0.19772355, 0.31180893, 0.15441733]])

In [29]:
np.abs(mat - mat.mean())

array([[0.19423554, 0.00391392, 0.37866936, 0.11955087, 0.32319702],
       [0.41244942, 0.46260594, 0.3448842 , 0.0956415 , 0.30424136],
       [0.40914859, 0.01784273, 0.01759938, 0.47496367, 0.23629476],
       [0.05890054, 0.45605546, 0.24066755, 0.42816169, 0.01235269],
       [0.5218551 , 0.20904863, 0.23733961, 0.12325422, 0.28064582]])

In [30]:
np.abs(mat - mat.mean()) > 1.5*mat.std()

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False]])

In [31]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([0.89766909, 0.91002682, 0.89111861, 0.95691825])

In [32]:
v = np.arange(12).reshape((4,3))

In [33]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [35]:
v.shape()

TypeError: 'tuple' object is not callable

In [36]:
v.any

<function ndarray.any>

In [37]:
v.any()

True

In [38]:
v.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [39]:
v.all()

False

In [40]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [41]:
v[(0,0)] = 12

In [42]:
v

array([[12,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
v.prod()

479001600

In [46]:
v1 = v.copy()

In [47]:
v1[0,0] = 1234

In [48]:
v1

array([[1234,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [49]:
v

array([[12,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [51]:
v2 = np.loads(data)
v2

<ipython-input-51-b770a7d8cac2>:1: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
  v2 = np.loads(data)


array([[12,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
 v = np.arange(-3,3)

In [54]:
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [55]:
v

array([-3, -2, -1,  0,  1,  2])